"""String templates for ``krossdb schema init-migrations`` scaffolding.

Kept separate from :mod:`krossdb.migrations.support` (and free of any
``alembic`` import) so the CLI can render these without the ``migrations``
extra installed, and so tests can assert on the generated content directly.
"""

from __future__ import annotations

_ENV_PY_TEMPLATE = '''\
"""Alembic environment, wired to krossdb's own connection config.

Generated by ``krossdb schema init-migrations``. Day-to-day migration work
still goes through the standard ``alembic`` CLI (revision/upgrade/downgrade/
history) — this file only resolves the database URL and target metadata from
krossdb instead of a hardcoded ``sqlalchemy.url`` in alembic.ini.
"""

from __future__ import annotations

import importlib
from logging.config import fileConfig

from alembic import context

from krossdb.migrations import configure

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_module_path, _, _attr = "{metadata_path}".partition(":")
_module = importlib.import_module(_module_path)
target_metadata = getattr(_module, _attr)

configure(target_metadata, connection_name="{connection}", config_path="{config_path}")
'''

SCRIPT_PY_MAKO = '''\
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''

_ALEMBIC_INI_TEMPLATE = """\
[alembic]
script_location = {alembic_dir}
prepend_sys_path = .

# krossdb sets sqlalchemy.url at runtime (see alembic/env.py) from
# krossdb.yaml's {connection!r} connection, so no URL is hardcoded here.

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""


def render_env_py(*, metadata_path: str, connection: str, config_path: str) -> str:
    return _ENV_PY_TEMPLATE.format(
        metadata_path=metadata_path,
        connection=connection,
        config_path=config_path,
    )


def render_alembic_ini(*, alembic_dir: str, connection: str) -> str:
    return _ALEMBIC_INI_TEMPLATE.format(alembic_dir=alembic_dir, connection=connection)


__all__ = ["SCRIPT_PY_MAKO", "render_alembic_ini", "render_env_py"]
